#!/usr/bin/env python3
"""Generate link glue for the non-matching port build.

After the game and port objects are compiled, some symbols are still
undefined. This script resolves them in two ways:

1. BSS/SBSS globals. The matching build emits these from config/symbols.txt
   as assembly (tools/gen_bss.py). Here they are laid out in a single
   block that keeps their original relative addresses, so out-of-bounds
   accesses into neighbouring variables behave as on the PS1.

2. Everything else that the toolchain libraries do not provide. These are
   PsyQ SDK functions and data that the port layer does not implement yet.
   They get logging stubs, so the build always links and the log shows
   which SDK calls are still missing.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

import yaml

# End of the main executable's .text (config/main.yaml: 0x80090800 + 0x83260).
MAIN_TEXT_END = 0x80113A60
MAX_DATA_STUB = 0x10000


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--nm', required=True, help='nm for the target')
    p.add_argument('--prefix', default='', help='C symbol prefix (e.g. _)')
    p.add_argument('--symbols', required=True, type=Path)
    p.add_argument('--bss', required=True, type=Path)
    p.add_argument('--sbss', required=True, type=Path)
    p.add_argument('--lib', action='append', default=[],
                   help='archive whose definitions are not stubbed')
    p.add_argument('--out-asm', required=True, type=Path)
    p.add_argument('--out-stubs', required=True, type=Path)
    p.add_argument('--report', type=Path, help='write a summary here')
    p.add_argument('objects', nargs='+', type=Path)
    return p.parse_args()


def run_nm(nm, path, *flags):
    out = subprocess.run([nm, *flags, str(path)], check=True,
                         capture_output=True, text=True).stdout
    return out.splitlines()


def object_symbols(nm, objects):
    defined, undefined = set(), set()
    for obj in objects:
        for line in run_nm(nm, obj):
            parts = line.split()
            if len(parts) == 2 and parts[0] == 'U':
                undefined.add(parts[1])
            elif len(parts) == 3 and parts[1] not in ('U', 'w'):
                defined.add(parts[2])
    return defined, undefined - defined


def archive_symbols(nm, archive):
    names = set()
    for line in run_nm(nm, archive, '-g', '--defined-only'):
        parts = line.split()
        if len(parts) == 3:
            names.add(parts[2])
    return names


def load_symbol_map(path):
    syms = {}
    for line in path.read_text().splitlines():
        m = re.match(r'\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;(.*)', line)
        if not m:
            continue
        size = re.search(r'size:(0x[0-9A-Fa-f]+|\d+)', m.group(3))
        syms[m.group(1)] = (int(m.group(2), 16),
                            int(size.group(1), 0) if size else None)
    return syms


def main():
    args = parse_args()
    pre = args.prefix

    def strip(name):
        return name[len(pre):] if pre and name.startswith(pre) else name

    _, undefined = object_symbols(args.nm, args.objects)
    libs = set()
    for lib in args.lib:
        libs |= archive_symbols(args.nm, lib)
    undefined = {u for u in undefined if u not in libs}
    names = sorted(strip(u) for u in undefined)

    syms = load_symbol_map(args.symbols)
    sbss = yaml.safe_load(args.sbss.read_text())
    bss = yaml.safe_load(args.bss.read_text())
    # SBSS and BSS are adjacent; treat them as one block.
    assert sbss['end'] == bss['start']
    block_start = sbss['start'] & ~0xF
    block_end = bss['end']
    addrs = sorted(a for a, _ in syms.values())

    def gap_size(addr):
        nxt = next((a for a in addrs if a > addr), addr + 4)
        return max(4, min(nxt - addr, MAX_DATA_STUB))

    bss_syms, func_stubs, data_stubs, unknown = [], [], [], []
    for name in names:
        if name not in syms:
            unknown.append(name)
            continue
        addr, size = syms[name]
        if block_start <= addr < block_end:
            bss_syms.append((addr, name))
        elif addr < MAIN_TEXT_END:
            func_stubs.append(name)
        else:
            data_stubs.append((name, size or gap_size(addr)))

    # Unknown names (not in the symbol map) are assumed to be functions.
    func_stubs += unknown

    asm = [
        '/* Generated by port/tools/gen_glue.py. Do not edit. */',
        '/* Game SBSS+BSS globals at their original relative addresses. */',
        '\t.bss',
        '\t.balign 16',
        f'\t.globl {pre}dw_main_bss',
        f'{pre}dw_main_bss:',
        f'\t.space 0x{block_end - block_start:X}',
    ]
    for addr, name in sorted(bss_syms):
        asm.append(f'\t.globl {pre}{name}')
        asm.append(f'\t.set {pre}{name}, {pre}dw_main_bss + 0x{addr - block_start:X}')
    # No executable stack (GNU/Linux linkers warn otherwise).
    asm.append('\t.section .note.GNU-stack,"",@progbits')
    args.out_asm.parent.mkdir(parents=True, exist_ok=True)
    args.out_asm.write_text('\n'.join(asm) + '\n')

    stubs = [
        '/* Generated by port/tools/gen_glue.py. Do not edit. */',
        '/*',
        ' * Unimplemented PsyQ SDK functions and data. Each function logs its',
        ' * first call and returns 0. Declared without prototypes on purpose:',
        ' * callers use their own declarations.',
        ' */',
        'void dw_stub_called(const char *name);',
        '',
        '#define STUB(name) \\',
        '\tint name() \\',
        '\t{ \\',
        '\t\tstatic int called; \\',
        '\t\tif (!called) { \\',
        '\t\t\tcalled = 1; \\',
        '\t\t\tdw_stub_called(#name); \\',
        '\t\t} \\',
        '\t\treturn 0; \\',
        '\t}',
        '',
    ]
    stubs += [f'STUB({n})' for n in func_stubs]
    if data_stubs:
        stubs.append('')
        stubs.append('/* Data: zero-filled placeholders sized from symbols.txt. */')
        stubs += [f'unsigned char {n}[{s}] __attribute__((aligned(8)));'
                  for n, s in data_stubs]
    args.out_stubs.write_text('\n'.join(stubs) + '\n')

    summary = (f'gen_glue: {len(bss_syms)} BSS globals, '
               f'{len(func_stubs)} stubbed functions '
               f'({len(unknown)} not in symbols.txt), '
               f'{len(data_stubs)} stubbed data symbols')
    print(summary)
    if args.report:
        lines = [summary, '', 'Stubbed functions:']
        lines += [f'  {n}' for n in func_stubs]
        lines += ['', 'Stubbed data:'] + [f'  {n} [{s}]' for n, s in data_stubs]
        args.report.write_text('\n'.join(lines) + '\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
